package Dsl.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '7f979d2a-d5d4-41fe-9927-5316d28080d1' (id = 'Dsl_Build')
accordingly and delete the patch script.
*/
changeBuildType("7f979d2a-d5d4-41fe-9927-5316d28080d1") {
    params {
        add {
            password("Pass", "credentialsJSON:14836c1f-fd23-4da0-ae40-5a1916871658", label = "Pass")
        }
        add {
            checkbox("test", "", label = "one", display = ParameterDisplay.PROMPT,
                      checked = "true")
        }
        add {
            checkbox("three", "three", label = "three", display = ParameterDisplay.PROMPT,
                      checked = "true")
        }
        add {
            checkbox("two", "two", label = "two", display = ParameterDisplay.PROMPT,
                      checked = "false")
        }
    }
}
